server:
    port: 8080
    # port: ${server.port}
spring:
    #数据源
    datasource:
        #    username: root
        #password: root
        #url: jdbc:mysql://localhost:3306/datax_web?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=false&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=UTF-8
        password: 123456
        username: root
        url: jdbc:mysql://localhost:3306/datax_web?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&useSSL=false&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            initial-size: 5
            min-idle: 5
            max-active: 10
            max-wait: 60000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            use-global-data-source-stat: true
            min-evictable-idle-time-millis: 300000
            time-between-eviction-runs-millis: 60000
            max-open-prepared-statements: 20
            max-pool-prepared-statement-per-connection-size: 20
            remove-abandoned-timeout: 180
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

mybatis-plus:
    # mapper.xml文件扫描
    mapper-locations: classpath*:/mybatis-mapper/*Mapper.xml
    # 实体扫描，多个package用逗号或者分号分隔
    #typeAliasesPackage: com.yibo.essyncclient.*.entity
    global-config:
        # 数据库相关配置
        db-config:
            # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: AUTO
            # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
            field-strategy: NOT_NULL
            # 驼峰下划线转换
            column-underline: true
            # 逻辑删除
            logic-delete-value: 0
            logic-not-delete-value: 1
            # 数据库类型
            db-type: mysql
        banner: false
    # mybatis原生配置
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true
        jdbc-type-for-null: 'null'
        type-handlers-package: com.wugui.datax.admin.core.handler


logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
        - appid:
          secret:
          # token: #微信小程序消息服务器配置的token
          # aesKey: #微信小程序消息服务器配置的EncodingAESKey
          # msgDataFormat: JSON
